name: "Build & Test"

on:
  workflow_dispatch: # on button click

jobs:
  test:
    strategy:
      matrix:
        node-version: [22]  # Add your desired versions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache dependencies
        id: cache-npm
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            node_modules
          key: deps-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            deps-${{ runner.os }}-${{ matrix.node-version }}-

      # Install dependencies only
      - run: npm ci
      - name: Start database for testing
        working-directory: "node_modules/@decaf-ts/for-couchdb"
        run: |
          npm run docker:build
          docker compose -f docker/docker-compose.yml up -d
      - name: Wait for all CouchDB nodes to be ready
        run: |
          for i in {1..10}; do
            echo "Checking CouchDB nodes (attempt $i)..."
            curl -sf http://localhost:10010/_up && \
            curl -sf http://localhost:10011/_up && \
            curl -sf http://localhost:10012/_up && break
            echo "One or more CouchDB nodes not ready yet..."
            sleep 3
          done
      - name: Cache Build
        id: cache-build
        uses: actions/cache@v4
        with:
          path: | 
            lib
            dist
          key: build-${{ runner.os }}-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            build-${{ runner.os }}-${{ matrix.node-version }}-
            
      - if: ${{ steps.cache-build.outputs.cache-hit != 'true' }}
        run: npm run build:prod  # Replace with your build command      

      - run: npm run test:all